### /hello-functional
GET http://localhost:8080/hello-functional

### /sample/hello
GET http://localhost:8080/sample/hello

### 사용자 등록
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Kevin An",
  "email": "kevin@gmail.com"
}

### 사용자 전체 조회
GET http://localhost:8080/users

### 사용자 단건 조회
GET http://localhost:8080/users/1

### 사용자 삭제
DELETE http://localhost:8080/users/2

### deleteUserByName
DELETE http://localhost:8080/users/search?name=Kevin An

### 사용자 정보 수정
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Tony Lee",
  "email": "tony@gmail.com"
}

### getPostContent
GET http://localhost:8080/posts/11

### getMultiPostContent
GET http://localhost:8080/posts/search-single?ids=1,2,3

### getParallelMultiPostContent
GET http://localhost:8080/posts/search-parallel?ids=1,2,3

### createPost
POST http://localhost:8080/v2/posts
Content-Type: application/json

{
  "userId": 3,
  "title": "타이틀입니다.",
  "content": "Spring Webflux 실습 "
}

### findAllPost
GET http://localhost:8080/v2/posts

### findPost
GET http://localhost:8080/v2/posts/1

### deletePost
DELETE http://localhost:8080/v2/posts/1

### getUserPosts
GET http://localhost:8080/users/3/posts